[package]
edition = "2024"
name = "first"
version = "0.1.0"

[dependencies]
anyhow = { version = "1.0.100", default-features = false }
argh = { version = "0.1.13", default-features = false }
clappen = { workspace = true, default-features = false }
